-- V23 (MySQL) 假期账本 decimal 化
ALTER TABLE leave_balance MODIFY COLUMN quota DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE leave_balance MODIFY COLUMN used DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE leave_balance MODIFY COLUMN frozen DECIMAL(10,2) NOT NULL DEFAULT 0;
ALTER TABLE leave_transaction MODIFY COLUMN delta DECIMAL(10,2) NOT NULL DEFAULT 0;
